name: Feature request
description: Suggest an improvement
title: "feature: "
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem and proposed solution
    validations:
      required: true
