from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipam', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(name="ImportSource", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100, unique=True)), ("slug", models.SlugField(unique=True)), ("source_type", models.CharField(choices=[("gestioip", "GestióIP"), ("phpipam", "phpIPAM"), ("generic_csv", "CSV"), ("generic_json", "JSON")], max_length=20)), ("enabled", models.BooleanField(default=True)), ("description", models.TextField(blank=True)), ("source_timezone", models.CharField(blank=True, max_length=64)), ("field_mapping", models.JSONField(blank=True, default=dict)), ("created", models.DateTimeField(auto_now_add=True)), ("last_updated", models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name="ImportJob", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("started", models.DateTimeField(auto_now_add=True)), ("completed", models.DateTimeField(blank=True, null=True)), ("status", models.CharField(choices=[("running", "Running"), ("completed", "Completed"), ("failed", "Failed"), ("dry_run", "Dry run")], default="running", max_length=20)), ("filename", models.CharField(blank=True, max_length=255)), ("file_hash", models.CharField(blank=True, max_length=64)), ("file_size", models.PositiveBigIntegerField(blank=True, null=True)), ("import_mode", models.CharField(choices=[("history_only", "History only"), ("inventory_history", "Inventory and history")], default="history_only", max_length=30)), ("total_records", models.PositiveIntegerField(default=0)), ("processed_records", models.PositiveIntegerField(default=0)), ("created_records", models.PositiveIntegerField(default=0)), ("updated_records", models.PositiveIntegerField(default=0)), ("skipped_records", models.PositiveIntegerField(default=0)), ("duplicate_records", models.PositiveIntegerField(default=0)), ("conflict_records", models.PositiveIntegerField(default=0)), ("error_records", models.PositiveIntegerField(default=0)), ("dry_run", models.BooleanField(default=False)), ("summary", models.JSONField(blank=True, default=dict)), ("error_details", models.JSONField(blank=True, default=list)), ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="jobs", to="netbox_ip_history.importsource")), ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="HistoricalIPEvent", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("timestamp", models.DateTimeField()), ("ip_address", models.GenericIPAddressField()), ("prefix_length", models.PositiveSmallIntegerField(blank=True, null=True)), ("vrf_name", models.CharField(blank=True, max_length=255)), ("vrf_rd", models.CharField(blank=True, max_length=255)), ("source_scope_identifier", models.CharField(blank=True, max_length=255)), ("tenant_name", models.CharField(blank=True, max_length=255)), ("event_type", models.CharField(max_length=30)), ("source_record_id", models.CharField(blank=True, max_length=255)), ("source_event_type", models.CharField(blank=True, max_length=255)), ("source_username", models.CharField(blank=True, max_length=255)), ("hostname", models.CharField(blank=True, max_length=255)), ("dns_name", models.CharField(blank=True, max_length=255)), ("description", models.TextField(blank=True)), ("owner_type", models.CharField(blank=True, max_length=64)), ("owner_name", models.CharField(blank=True, max_length=255)), ("interface_name", models.CharField(blank=True, max_length=255)), ("mac_address", models.CharField(blank=True, max_length=64)), ("device_name", models.CharField(blank=True, max_length=255)), ("virtual_machine_name", models.CharField(blank=True, max_length=255)), ("status", models.CharField(blank=True, max_length=255)), ("location", models.CharField(blank=True, max_length=255)), ("site", models.CharField(blank=True, max_length=255)), ("role", models.CharField(blank=True, max_length=255)), ("tags_snapshot", models.JSONField(blank=True, default=list)), ("custom_fields_snapshot", models.JSONField(default=dict)), ("raw_data", models.JSONField(default=dict)), ("fingerprint", models.CharField(max_length=64, unique=True)), ("import_job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="netbox_ip_history.importjob")), ("related_netbox_ip", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="ipam.ipaddress")), ("source", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="netbox_ip_history.importsource"))]),
        migrations.AddIndex(model_name="historicalipevent", index=models.Index(fields=["ip_address", "-timestamp"], name="netbox_ip_his_ip_addre_8b6d6c_idx")),
    ]