# Generated by Django 6.0.8 on 2026-08-30 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_ip_history', '0006_repair_native_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalipevent',
            options={'ordering': ('-timestamp', '-id')},
        ),
        migrations.AlterModelOptions(
            name='importjob',
            options={'ordering': ('-started',)},
        ),
        migrations.AlterModelOptions(
            name='importsource',
            options={'ordering': ('name',)},
        ),
        migrations.RenameIndex(
            model_name='historicalipevent',
            new_name='netbox_ip_h_ip_addr_883ca1_idx',
            old_name='netbox_ip_his_ip_addre_8b6d6c_idx',
        ),
        migrations.RenameIndex(
            model_name='historicalipevent',
            new_name='netbox_ip_h_source__577fd7_idx',
            old_name='netbox_ip_h_source__55f448_idx',
        ),
        migrations.RenameIndex(
            model_name='historicalipevent',
            new_name='netbox_ip_h_event_t_7b92da_idx',
            old_name='netbox_ip_h_event_t_2b31f7_idx',
        ),
        migrations.RenameIndex(
            model_name='historicalipevent',
            new_name='netbox_ip_h_vrf_nam_068191_idx',
            old_name='netbox_ip_h_vrf_nam_bdf416_idx',
        ),
        migrations.RenameIndex(
            model_name='historicalipevent',
            new_name='netbox_ip_h_import__1a5e0c_idx',
            old_name='netbox_ip_h_import__864436_idx',
        ),
    ]
